### ISSUE TITLE
May I use this in a Curseforge modpack?

### ISSUE THREAD

**Issue by MoonMoonShark** [a0a7/MagicFeatherReplumed#2]
hey there! i have a private server running a custom modpack that i made, and we've previously used Magic Feather in the past couple versions. we were very sad when it looked like it had been discontinued, but then i found you had made a new version and we all rejoiced.

unfortunately, the modpack is on curseforge, but your version of the mod is on modrinth, and when i try to upload the pack to curseforge it throws errors about the mod being the wrong version or an invalid project. i'm not sure if it's because your mod is hosted on modrinth, or if there's a setting there that would allow it, or if it's because it's referencing an old mod on curseforge that doesn't have a version for 1.19, or if there's something else altogether. 

i appreciate all of your work on this, and i really hope we can figure out how to get it all running. please let me know if there is anything i can do to help!

if you're interested in checking it out before you approve, here's the modpack: https://legacy.curseforge.com/minecraft/modpacks/the-lighthouse

**Comment by a0ax** [comment]
On Curseforge now! 

Modpacks are definitely allowed--see [LICENSE](https://github.com/sudolev/MagicFeatherReplumed/blob/1.19.2/LICENSE).

Appreciate you using the mod!
